//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiColmap.Data_Access.Entity_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities1 : DbContext
    {
        public DataBaseEntities1()
            : base("name=DataBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<map_tblDicDepartamentos> map_tblDicDepartamentos { get; set; }
        public virtual DbSet<map_tblDicTamanos> map_tblDicTamanos { get; set; }
        public virtual DbSet<map_tblCoordinates> map_tblCoordinates { get; set; }
        public virtual DbSet<map_tblFeatures> map_tblFeatures { get; set; }
        public virtual DbSet<map_tblGeometry> map_tblGeometry { get; set; }
        public virtual DbSet<map_tblProperties> map_tblProperties { get; set; }
    }
}
