//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiColmap.Data_Access.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_tblCoordinates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public map_tblCoordinates()
        {
            this.map_tblGeometry = new HashSet<map_tblGeometry>();
        }
    
        public int co_idCoordinate_pk { get; set; }
        public float co_longitude { get; set; }
        public float co_latitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<map_tblGeometry> map_tblGeometry { get; set; }
    }
}
