//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiColmap.Data_Access.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class map_tblDicDepartamentos
    {
        public int dide_id_pk { get; set; }
        public string dide_nombre { get; set; }
        public bool dide_estado { get; set; }
    }
}
